### ISSUE TITLE
More detailed addon descriptions

### ISSUE THREAD

**Issue by mastercake10** [BentoBoxWorld/website#12]
Most addon descriptions are quite basic at this point, and do not explain the purpose well (See Magiccobblestonegenerator for example).

**Comment by Poslovitch** [comment]
We might want to write them by ourselves, so that it looks nice.

**Comment by Poslovitch** [comment]
I've rewritten all the descriptions to (at least) basically explain what the addon does. There is still room for improvement, but it's a good start. Closing.
