### ISSUE TITLE
Limits addon is not available on the "Custom" page

### ISSUE THREAD

**Issue by Poslovitch** [BentoBoxWorld/website#15]
#### Describe the bug

The Limits addon is not displayed on the "Custom" page, although having been added to the addons list internally (https://github.com/BentoBoxWorld/website/commit/cc62dd00ec4f6362dbb5bfd0a0a0fe5b77772c23).

**Comment by mastercake10** [comment]
Apparently, Limits is not listed on the codemc repo:
https://repo.codemc.io/service/rest/repository/browse/maven-releases/world/bentobox/

**Comment by tastybento** [comment]
Weird. Okay, I'll do a release and let's see if that fixes it.

**Comment by tastybento** [comment]
It didn't. I'm asking Gabriel on his discord. I must be missing something.

**Comment by Poslovitch** [comment]
Is there the install command in the build parameters on the CI? I might have overlooked it.

**Comment by tastybento** [comment]
Limits is now in the list. https://repo.codemc.io/service/rest/repository/browse/maven-releases/world/bentobox/

**Comment by tastybento** [comment]
The fix is that in the CI, change the maven build goals from package to deploy
