### ISSUE TITLE
Support 1.12.2

### ISSUE THREAD

**Issue by StarDream521** [BentoBoxWorld/website#23]
Can the plug-in be backward compatible?

**Comment by Fredthedoggy** [comment]
First, Why is this on the website repo?
Second, No. BentoBox only supports the Latest Minecraft Version(s)
If you really want 1.12.2, use [TastyBento's ASkyBlock](https://github.com/tastybento/askyblock) (Archived)

**Comment by StarDream521** [comment]
Ok thanks for your answer
